REP_DATA = {
    "Amie Albergo": {
        "display_name": "Amie!",
        "full_name": "Amie Albergo",
        "email": "amie.albergo@gawk.com.au",
        "phone": "0423 410 245",
    },
    "Chris Farnon": {
        "display_name": "Chris!",
        "full_name": "Chris Farnon",
        "email": "chris.farnon@gawk.com.au",
        "phone": "0478 002 708",
    },
    "Dan McCann": {
        "display_name": "Dan!",
        "full_name": "Dan McCann",
        "email": "dan.mccann@gawk.com.au",
        "phone": "0413 338 367",
    },
    "Daniel McCann": {
        "display_name": "Dan!",
        "full_name": "Dan McCann",
        "email": "dan.mccann@gawk.com.au",
        "phone": "0413 338 367",
    },
    "Gabby Bowles": {
        "display_name": "Gabby!",
        "full_name": "Gabby Bowles",
        "email": "gabby.bowles@gawk.com.au",
        "phone": "0411 175 211",
    },
    "Heidi Lawrie": {
        "display_name": "Heidi!",
        "full_name": "Heidi Lawrie",
        "email": "heidi.lawrie@gawk.com.au",
        "phone": "0410 479 690",
    },
    "Isabella Camm": {
        "display_name": "Isabella!",
        "full_name": "Isabella Camm",
        "email": "isabella.camm@gawk.com.au",
        "phone": "0490 749 878",
    },
    "James Course": {
        "display_name": "James!",
        "full_name": "James Course",
        "email": "james@gawk.com.au",
        "phone": "0400 096 182",
    },
    "Karen Jones": {
        "display_name": "Karen!",
        "full_name": "Karen Jones",
        "email": "karen.jones@gawk.com.au",
        "phone": "0400 270 046",
    },
    "Luke Course": {
        "display_name": "Luke!",
        "full_name": "Luke Course",
        "email": "luke@gawk.com.au",
        "phone": "0431 304 043",
    },
    "Matt Tyler": {
        "display_name": "Matt!",
        "full_name": "Matt Tyler",
        "email": "matt@gawk.com.au",
        "phone": "0422 102 199",
    },
    "Matthew Tyler": {
        "display_name": "Matt!",
        "full_name": "Matt Tyler",
        "email": "matt@gawk.com.au",
        "phone": "0422 102 199",
    },
    "Mitchell Madeley": {
        "display_name": "Mitchell!",
        "full_name": "Mitchell Madeley",
        "email": "mitch.madeley@gawk.com.au",
        "phone": "0450 273 879",
    },
    "Nathan Quick": {
        "display_name": "Nathan!",
        "full_name": "Nathan Quick",
        "email": "nathan.quick@gawk.com.au",
        "phone": "0409 788 043",
    },
    "Peter Upton": {
        "display_name": "Peter!",
        "full_name": "Peter Upton",
        "email": "pete@gawk.com.au",
        "phone": "0409 973 518",
    },
    "Phil Zumbo": {
        "display_name": "Phil!",
        "full_name": "Phil Zumbo",
        "email": "phil@gawk.com.au",
        "phone": "0411 403 098",
    },
    "Phillip Zumbo": {
        "display_name": "Phil!",
        "full_name": "Phil Zumbo",
        "email": "phil@gawk.com.au",
        "phone": "0411 403 098",
    },
    "Rebecca Ragheb": {
        "display_name": "Rebecca!",
        "full_name": "Rebecca Ragheb",
        "email": "rebecca@gawk.com.au",
        "phone": "0422 116 936",
    },
    "Sam Brown": {
        "display_name": "Sam!",
        "full_name": "Sam Brown",
        "email": "sam.brown@gawk.com.au",
        "phone": "0423 632 004",
    },
    "Sam Liistro": {
        "display_name": "Sam!",
        "full_name": "Sam Liistro",
        "email": "sam.liistro@gawk.com.au",
        "phone": "0423 449 937",
    },
    "Stefan Vukelic": {
        "display_name": "Stefan!",
        "full_name": "Stefan Vukelic",
        "email": "stefan.vukelic@gawk.com.au",
        "phone": "0422 069 613",
    },
    "Stephen Breheny": {
        "display_name": "Stephen!",
        "full_name": "Stephen Breheny",
        "email": "stephen.breheny@gawk.com.au",
        "phone": "0448 996 453",
    },
    "Tim Stevenson": {
        "display_name": "Tim!",
        "full_name": "Tim Stevenson",
        "email": "tim@gawk.com.au",
        "phone": "0404 999 238",
    },
    "Will Hamilton": {
        "display_name": "Will!",
        "full_name": "Will Hamilton",
        "email": "will@gawk.com.au",
        "phone": "0411 404 616",
    },
    "Zoe Fenaughty": {
        "display_name": "Zoe!",
        "full_name": "Zoe Fenaughty",
        "email": "zoe.fenaughty@gawk.com.au",
        "phone": "0417 105 934",
    },
}

DROPDOWN_REPS = [
    "Amie Albergo",
    "Chris Farnon",
    "Dan McCann",
    "Gabby Bowles",
    "Heidi Lawrie",
    "Isabella Camm",
    "James Course",
    "Karen Jones",
    "Luke Course",
    "Matt Tyler",
    "Mitchell Madeley",
    "Nathan Quick",
    "Peter Upton",
    "Phil Zumbo",
    "Rebecca Ragheb",
    "Sam Brown",
    "Sam Liistro",
    "Stefan Vukelic",
    "Stephen Breheny",
    "Stephen Walker",
    "Tim Stevenson",
    "Will Hamilton",
    "Zoe Fenaughty",
]
